development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rentamovie_development
  username: develop
  password: develop
  
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rentamovie_development
  username: develop
  password: develop